server:
    port: 8071
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/afrid786/config-server
          default-label: master
          search-paths:
            - src/main/resources/config

  profiles:
    active:
      - git


